import type { Message } from '@/lib/types'

export function exportChatToPdf(messages: Message[], conversationId: string) {
  if (!messages || messages.length === 0) return

  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })

  const messagesHtml = messages
    .map((msg, index) => {
      const isUser = msg.role === 'user'
      const sourcesHtml =
        msg.sources && msg.sources.length > 0
          ? `<div style="margin-top:8px;padding-top:8px;border-top:1px dashed #e2e8f0;font-size:11px;color:#0F6E56;">
              <strong>Cited NBR References:</strong> ${msg.sources.map((s) => `${s.source} (${s.section || 'General'})`).join(', ')}
             </div>`
          : ''

      return `
        <div style="margin-bottom:16px;padding:14px 18px;border-radius:12px;${
          isUser
            ? 'background:#f0fdf4;border:1px solid #bbf7d0;color:#166534;'
            : 'background:#ffffff;border:1px solid #e2e8f0;color:#1e293b;'
        }">
          <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px;color:${
            isUser ? '#166534' : '#0F6E56'
          }">
            ${isUser ? 'Taxpayer Query' : 'AykorGPT Advisory Answer'} #${index + 1}
          </div>
          <div style="font-size:13px;line-height:1.6;white-space:pre-wrap;">${msg.content}</div>
          ${sourcesHtml}
        </div>
      `
    })
    .join('')

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>AykorGPT Advisory Report - ${conversationId.slice(0, 8)}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #0f172a; max-width: 800px; margin: 0 auto; }
          .header { text-align: center; border-bottom: 2px solid #0F6E56; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { display: inline-block; background: #0F6E56; color: white; font-weight: bold; padding: 6px 12px; border-radius: 8px; font-size: 14px; margin-bottom: 8px; }
          .title { font-size: 22px; font-weight: 800; color: #0f172a; margin: 6px 0; }
          .meta { font-size: 12px; color: #64748b; margin-top: 4px; }
          .disclaimer { margin-top: 40px; padding: 12px 16px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 11px; color: #64748b; text-align: center; }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">AykorGPT</div>
          <div class="title">Tax Advisory & Compliance Summary Report</div>
          <div class="meta">Generated on ${dateStr} | Ref: ${conversationId}</div>
        </div>

        <div class="messages">
          ${messagesHtml}
        </div>

        <div class="disclaimer">
          <strong>Disclaimer:</strong> This report is generated by AykorGPT based on official National Board of Revenue (NBR) acts, SROs, and circulars for informational purposes only and does not constitute formal legal advice.
        </div>

        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `)

  printWindow.document.close()
}
